### ISSUE TITLE
Project is not open source without a license file

### ISSUE THREAD

**Issue by karan** [smitelli/scottsmitelli.com#1]
This repo is missing a license. Without a license, all code is copyright the author and may not be used by anyone else.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

**Comment by smitelli** [comment]
... You actually want to use this code for something?

**Comment by smitelli** [comment]
Okay, back to this thread. With all due respect, this is a stagnant personal project and I don't care.
